### ISSUE TITLE
Fronteers Conference

### ISSUE THREAD

**Issue by jayne-mast** [adunkman/confa11y#24]
Woohoo! Thanks for your interest in this project!

If you’re submitting an event, try to fill out as much information as possible:

```
title: Fronteers 2017
services: Live Captioning, Gender-Neutral bathrooms, Dietary Accommodation, Mobility Access, Service Animals Welcome, Transcript(s) after Event
site: http://fronteersconf.org
city: Amsterdam, The Netherlands
from: 2017-10-05
to: 2017-10-06
```

**Comment by nickttng** [comment]
@pverbeek thanks! just added to confa11y site and [tweeted it](https://twitter.com/confa11y/status/882993604196806656).
